### ISSUE TITLE
Cannot sign in / Tweak for Login

### ISSUE THREAD

**Issue by vrodriguezf** [liberodark/stadia-app#2]
![image](https://user-images.githubusercontent.com/7083752/78796307-6e508180-79b6-11ea-8d1d-d90abdbeb9a2.png)

I'm trying the app on Ubuntu 18.04

Thanks!

**Comment by matteocrippa** [comment]
Same for me

**Comment by liberodark** [comment]
Oh that is strange. probably google block that...

**Comment by liberodark** [comment]
That is new update from google for block the app.
So sorry for that need to make other bypass.

**Comment by liberodark** [comment]
Only solution is use : "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/73.0" for login in dev mod = CTRL+SHIT+I

https://winaero.com/blog/change-user-agent-chrome/

That is just one time for login.

**Comment by gorfreed** [comment]
Confirmed, this app does not work because of a security block.
